import type {
  Contact,
  EventItem,
  NoteItem,
  Project,
  Reminder,
  TaskItem,
} from './types'

export const WEEK_DAYS = ['Mon', 'Tue', 'Wed', 'Thu', 'Fri']
export const WEEK_DATES = ['25', '26', '27', '28', '29']
export const TODAY_INDEX = 2
/** where the "now" line sits on the calendar, in decimal hours */
export const NOW_HOUR = 11.6
export const CALENDAR_START = 8
export const CALENDAR_END = 20

export const projects: Project[] = [
  { id: 'q3', name: 'Q3 Launch', color: 'var(--color-amber)' },
  { id: 'web', name: 'Website', color: 'var(--color-iris)' },
  { id: 'personal', name: 'Personal', color: 'var(--color-sage)' },
  { id: 'research', name: 'Research', color: 'var(--color-rose)' },
]

export const projectCounts: Record<string, number> = {
  q3: 12,
  web: 7,
  personal: 4,
  research: 3,
}

export const contacts: Contact[] = [
  {
    id: 'me',
    name: 'Honza V.',
    initials: 'HV',
    tintBg: '#3a3252',
    tintFg: '#c9c4e4',
  },
  {
    id: 'sarah',
    name: 'Sarah Kim',
    initials: 'SK',
    role: 'Finance · approver',
    tintBg: '#33404a',
    tintFg: '#a9c6d4',
  },
  {
    id: 'ana',
    name: 'Ana Ruiz',
    initials: 'AR',
    role: 'from “Pricing sync” event',
    tintBg: '#3d3a2e',
    tintFg: '#d6c9a2',
  },
]

const pricingReminders: Reminder[] = [
  {
    id: 'rem-1',
    kind: 'context',
    label: 'When finance replies in thread',
    detail: 'Context trigger · active',
    state: 'active',
  },
  {
    id: 'rem-2',
    kind: 'time',
    label: '2 hours before due',
    detail: 'Fri, 29 Aug · 13:00',
    state: 'upcoming',
  },
  {
    id: 'rem-3',
    kind: 'escalation',
    label: 'Escalate to Slack DM',
    detail: 'If not done by Fri · 15:00',
    state: 'active',
  },
]

export const tasks: TaskItem[] = [
  {
    id: 't-pricing',
    kind: 'task',
    title: 'Finalize pricing page copy',
    code: 'TASK-238',
    projectId: 'q3',
    source: 'gmail',
    status: 'in_progress',
    start: 'Thu, 28 Aug',
    due: 'Fri, 29 Aug · 15:00',
    description:
      'Rewrite the three tier descriptions to match the messaging from the finance thread — lead with outcomes, drop the seat-based framing, keep each under 60 words.\n\nOpen question: do we show annual pricing by default? See the linked note for context.',
    tags: ['copy'],
    suggestedTags: ['pricing', 'revenue'],
    blockedBy: ['t-approval'],
    blocks: ['t-publish', 't-announce'],
    linkedNoteIds: ['n-messaging', 'n-openq', 'n-competitor'],
    contactIds: ['sarah', 'ana'],
    reminders: pricingReminders,
    suggestedTime: {
      label: 'Thu, 28 Aug, 10:00–12:00',
      reason:
        'Your only open 2-hour focus block before the deadline, and it clears the conflict with Client call.',
    },
    conflict: 'Client call — Meridian',
    activity: [
      { at: '1h', text: 'You linked note “Competitor teardown”' },
      { at: '3h', text: 'Reminder escalated — no reply in finance thread' },
      { at: 'Mon', text: 'Created from email “Re: pricing page copy”' },
    ],
  },
  {
    id: 't-approval',
    kind: 'task',
    title: 'Pricing approval from finance',
    projectId: 'q3',
    status: 'blocked',
    tags: [],
    blockedBy: [],
    blocks: ['t-pricing'],
    linkedNoteIds: [],
    contactIds: ['sarah'],
    reminders: [],
    activity: [],
  },
  {
    id: 't-publish',
    kind: 'task',
    title: 'Publish pricing page',
    projectId: 'q3',
    status: 'todo',
    tags: [],
    blockedBy: ['t-pricing'],
    blocks: [],
    linkedNoteIds: [],
    contactIds: ['me'],
    reminders: [],
  },
  {
    id: 't-announce',
    kind: 'task',
    title: 'Announce in #launch',
    projectId: 'q3',
    source: 'slack',
    status: 'todo',
    tags: [],
    blockedBy: ['t-pricing'],
    blocks: [],
    linkedNoteIds: [],
    contactIds: [],
    reminders: [],
  },
  {
    id: 't-og',
    kind: 'task',
    title: 'Update OG share images',
    projectId: 'web',
    status: 'todo',
    due: 'Thu',
    tags: [],
    blockedBy: [],
    blocks: [],
    linkedNoteIds: [],
    contactIds: [],
    reminders: [],
  },
  {
    id: 't-qa',
    kind: 'task',
    title: 'QA the checkout flow',
    projectId: 'web',
    status: 'todo',
    checklist: { done: 2, total: 6 },
    tags: [],
    blockedBy: [],
    blocks: [],
    linkedNoteIds: [],
    contactIds: [],
    reminders: [],
  },
  {
    id: 't-analytics',
    kind: 'task',
    title: 'Migrate analytics events',
    projectId: 'web',
    status: 'in_progress',
    checklist: { done: 4, total: 7 },
    tags: [],
    blockedBy: [],
    blocks: [],
    linkedNoteIds: [],
    contactIds: ['me'],
    reminders: [],
  },
  {
    id: 't-email',
    kind: 'task',
    title: 'Draft launch email',
    projectId: 'q3',
    source: 'gmail',
    status: 'in_progress',
    tags: [],
    blockedBy: [],
    blocks: [],
    linkedNoteIds: [],
    contactIds: [],
    reminders: [],
  },
  {
    id: 't-legal',
    kind: 'task',
    title: 'Legal review of ToS changes',
    projectId: 'research',
    status: 'blocked',
    tags: [],
    blockedBy: [],
    blocks: [],
    linkedNoteIds: [],
    contactIds: [],
    reminders: [],
  },
  {
    id: 't-send',
    kind: 'task',
    title: 'Send pricing draft to finance',
    projectId: 'q3',
    source: 'gmail',
    status: 'todo',
    due: '14:00',
    tags: [],
    blockedBy: ['t-approval'],
    blocks: [],
    linkedNoteIds: [],
    contactIds: ['sarah'],
    reminders: [],
  },
  {
    id: 't-meridian',
    kind: 'task',
    title: 'Review Meridian contract',
    projectId: 'research',
    source: 'slack',
    status: 'todo',
    due: '16:30',
    tags: [],
    blockedBy: [],
    blocks: [],
    linkedNoteIds: [],
    contactIds: [],
    reminders: [],
  },
  {
    id: 't-ana',
    kind: 'task',
    title: 'Reply to Ana re: venue',
    projectId: 'personal',
    source: 'gmail',
    status: 'todo',
    tags: [],
    blockedBy: [],
    blocks: [],
    linkedNoteIds: [],
    contactIds: ['ana'],
    reminders: [],
  },
  {
    id: 't-slides',
    kind: 'task',
    title: 'Prep roadmap slides',
    projectId: 'q3',
    source: 'notion',
    status: 'todo',
    due: 'EOD',
    tags: [],
    blockedBy: [],
    blocks: [],
    linkedNoteIds: [],
    contactIds: [],
    reminders: [],
  },
  {
    id: 't-flights',
    kind: 'task',
    title: 'Book flights for offsite',
    projectId: 'personal',
    status: 'done',
    tags: [],
    blockedBy: [],
    blocks: [],
    linkedNoteIds: [],
    contactIds: [],
    reminders: [],
  },
  {
    id: 't-footer',
    kind: 'task',
    title: 'Fix broken link in footer',
    projectId: 'web',
    source: 'gmail',
    status: 'todo',
    unsorted: true,
    capturedAgo: '4h',
    tags: [],
    blockedBy: [],
    blocks: [],
    linkedNoteIds: [],
    contactIds: [],
    reminders: [],
  },
  {
    id: 't-launchdate',
    kind: 'task',
    title: 'Set the launch date',
    projectId: 'q3',
    status: 'done',
    tags: [],
    blockedBy: [],
    blocks: [],
    linkedNoteIds: [],
    contactIds: [],
    reminders: [],
  },
  {
    id: 't-support',
    kind: 'task',
    title: 'Brief the support team',
    projectId: 'q3',
    status: 'done',
    tags: [],
    blockedBy: [],
    blocks: [],
    linkedNoteIds: [],
    contactIds: [],
    reminders: [],
  },
  {
    id: 't-hero',
    kind: 'task',
    title: 'Finalize hero illustration',
    projectId: 'web',
    status: 'done',
    tags: [],
    blockedBy: [],
    blocks: [],
    linkedNoteIds: [],
    contactIds: [],
    reminders: [],
  },
]

export const notes: NoteItem[] = [
  {
    id: 'n-messaging',
    kind: 'note',
    title: 'Pricing messaging — finance sync',
    projectId: 'q3',
    source: 'gmail',
    tags: ['pricing'],
    snippet:
      '…agreed to lead with ROI language and remove per-seat framing across all tiers…',
    links: [],
    backlinks: ['t-pricing'],
  },
  {
    id: 'n-openq',
    kind: 'note',
    title: 'Q3 Launch / open questions',
    projectId: 'q3',
    tags: [],
    snippet:
      '…annual vs monthly default still undecided — blocked on [[Finalize pricing page copy]]…',
    links: ['t-pricing'],
    backlinks: [],
  },
  {
    id: 'n-competitor',
    kind: 'note',
    title: 'Competitor teardown',
    projectId: 'research',
    tags: ['research'],
    snippet:
      '…three of five competitors show annual pricing by default on the page…',
    links: [],
    backlinks: ['t-pricing'],
  },
  {
    id: 'n-onboard',
    kind: 'note',
    title: 'Bundle onboarding into Pro tier',
    source: 'slack',
    unsorted: true,
    capturedAgo: '2h',
    tags: [],
    snippet: 'Quick thought from the #product channel — worth a proper writeup.',
    links: [],
    backlinks: [],
  },
]

export const events: EventItem[] = [
  { id: 'e1', kind: 'event', title: 'Design critique', projectId: 'web', day: 0, startH: 10, endH: 11, tags: [], contactIds: [] },
  { id: 'e2', kind: 'event', title: 'Gym', projectId: 'personal', day: 0, startH: 17, endH: 18, tags: [], contactIds: [] },
  { id: 'e3', kind: 'event', title: 'Sprint planning', projectId: 'q3', day: 1, startH: 9.5, endH: 11, tags: [], contactIds: [] },
  { id: 'e4', kind: 'event', title: 'Lunch w/ Ana', projectId: 'personal', day: 1, startH: 12.5, endH: 13.5, tags: [], contactIds: ['ana'] },
  { id: 'e5', kind: 'event', title: 'Standup', projectId: 'q3', day: 2, startH: 9, endH: 9.33, tags: [], contactIds: [] },
  { id: 'e6', kind: 'event', title: 'Pricing review', projectId: 'q3', day: 2, startH: 11, endH: 12, tags: [], contactIds: ['sarah'] },
  { id: 'e7', kind: 'event', title: 'Focus — pricing copy', day: 2, startH: 13, endH: 15, tags: [], contactIds: [], accent: 'sage' },
  { id: 'e8', kind: 'event', title: 'Client call — Meridian', day: 2, startH: 14, endH: 15, tags: [], contactIds: [], accent: 'rose', conflict: 'Focus — pricing copy' },
  { id: 'e9', kind: 'event', title: '1:1 with Sarah', projectId: 'web', day: 3, startH: 10, endH: 10.5, tags: [], contactIds: ['sarah'] },
  { id: 'e10', kind: 'event', title: 'Roadmap workshop', projectId: 'q3', day: 3, startH: 14, endH: 16, tags: [], contactIds: [] },
  { id: 'e11', kind: 'event', title: 'Pricing page live', day: 4, startH: 12, endH: 12, tags: [], contactIds: [], accent: 'amber', milestone: true },
  { id: 'e12', kind: 'event', title: 'Review & deploy', projectId: 'web', day: 4, startH: 15, endH: 16, tags: [], contactIds: [] },
  { id: 'e-coffee', kind: 'event', title: 'Coffee with recruiter', day: 2, startH: 0, endH: 0, tags: [], contactIds: [], unsorted: true, needsTime: true, capturedAgo: '1d' },
]

export const allItems = [...tasks, ...notes, ...events]

export function itemById(id: string) {
  return allItems.find((i) => i.id === id)
}
export function projectById(id?: string) {
  return projects.find((p) => p.id === id)
}
export function contactById(id: string) {
  return contacts.find((c) => c.id === id)
}
